## NumPy Array Attributes

In [1]:
import numpy as np

In [2]:
# seed for reproducibility
rng = np.random.default_rng(seed=1701)

In [3]:
x1 = rng.integers(10, size=6)
x2 = rng.integers(10, size=(3, 4))
x3 = rng.integers(10, size=(3, 4, 5))

In [4]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


## Array Indexing: Accessing Single Elements

**One-Dimensional Arrays**

In [5]:
x1

array([9, 4, 0, 3, 8, 6], dtype=int64)

In [6]:
x1[0]

9

In [7]:
x1[-1]

6

**Multidimensional Arrays**

In [8]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

In [9]:
# [row, column]
x2[0, 0]

3

In [10]:
x2[-1, -1]

9

**Assignment**

In [11]:
x2[0, 0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [12]:
# this will be truncated!
x1[0] = 3.14159
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

## Array Slicing: Accessing Subarrays

**One-Dimensional Subarrays**

In [13]:
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

In [14]:
print(x1[:3])
print(x1[3:])
print(x1[1:4])
print(x1[::2])
print(x1[1::2])

[3 4 0]
[3 8 6]
[4 0 3]
[3 0 8]
[4 3 6]


In [15]:
# reverse array
print(x1[::-1])
print(x1[4::-2])

[6 8 3 0 4 3]
[8 0 3]


**Multidimensional Subarrays**

In [16]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [17]:
x2[:2, :3]

array([[12,  1,  3],
       [ 4,  0,  2]], dtype=int64)

In [18]:
x2[:3, ::2]

array([[12,  3],
       [ 4,  2],
       [ 0,  6]], dtype=int64)

In [19]:
x2[::-1, ::-1]

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]], dtype=int64)

In [20]:
# column slice
print(x2[:, 0])

# row slice
print(x2[0, :])
print(x2[0])

[12  4  0]
[12  1  3  7]
[12  1  3  7]


**Subarrays as No-Copy Views**

In [21]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [22]:
x2_sub = x2[:2, :2]
x2_sub

array([[12,  1],
       [ 4,  0]], dtype=int64)

In [23]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  1],
       [ 4,  0]], dtype=int64)

In [24]:
x2

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

**Creating Copies of Arrays**

In [25]:
x2_sub_copy = x2[:2, 0:2].copy()

In [26]:
x2_sub_copy[0, 0] = 0
x2_sub_copy

array([[0, 1],
       [4, 0]], dtype=int64)

In [27]:
x2

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

## Reshaping of Arrays

In [28]:
grid = np.arange(1, 10).reshape(3, 3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
grid_view = grid.reshape(-1) # = reshape(9)
grid_view[0] = 99
grid

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

**Vector Reshape**

In [30]:
x = np.array([1, 2, 3])

In [31]:
# row vector
x.reshape(1, 3)

array([[1, 2, 3]])

In [32]:
# column vector
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [33]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [34]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

**Concatenation of Arrays**

In [35]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

# must have the same ndim
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

# concatinate along the first axis
np.concatenate((grid, grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [37]:
# concatinate along the second axis
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [38]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [39]:
y = np.array([[99], [99]])
# horizontally stack the arrays

np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [40]:
x = np.array([[0, 1], [2, 3]])
y = np.array([[4, 5], [6, 7]])

# stack the arrays depthwise
np.dstack((x, y))

array([[[0, 4],
        [1, 5]],

       [[2, 6],
        [3, 7]]])

**Splitting of Arrays**

In [41]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

# N split points leads to N + 1 subarrays
x1, x2, x3 = np.split(x, (3, 5))
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [42]:
grid = np.arange(1, 17).reshape((4, 4))
grid

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
upper, lower = np.vsplit(grid, [2])
print("Upper:", upper)
print("Lower:", lower)

Upper: [[1 2 3 4]
 [5 6 7 8]]
Lower: [[ 9 10 11 12]
 [13 14 15 16]]


In [44]:
upper, lower = np.hsplit(grid, [2])
print("Upper:", upper)
print("Lower:", lower)

Upper: [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Lower: [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [45]:
x = np.array(
    [
        [
            [0, 1, 2, 3],
            [4, 5, 6, 7],
            [8, 9, 10, 11],
            [12, 13, 14, 15],
        ]
    ]
)

# split the arrays depthwise
np.dsplit(x, [1])

[array([[[ 0],
         [ 4],
         [ 8],
         [12]]]),
 array([[[ 1,  2,  3],
         [ 5,  6,  7],
         [ 9, 10, 11],
         [13, 14, 15]]])]