### List in Python

In [1]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
[str(i) for i in range(10)]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [3]:
l3 = [True, "2", 3.0, 4]
[type(i) for i in l3]

[bool, str, float, int]

### Fixed-Type Arrays in Python

In [4]:
import array

array.array("i", range(10))

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Arrays from Python Lists

In [5]:
import numpy as np

In [6]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [7]:
np.array([1.5, 2, 3, 4])

array([1.5, 2. , 3. , 4. ])

In [8]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [9]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [10]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.full(((3, 5)), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
np.random.random((3, 3))

array([[0.77767908, 0.61857603, 0.57028664],
       [0.89312525, 0.20414476, 0.10097596],
       [0.54547208, 0.02003238, 0.24778168]])

In [16]:
# random normal destribution
# mean = 0 | standard division = 1
np.random.normal(0, 1, (3, 3))

array([[ 1.38288812, -1.62274891, -0.79503377],
       [-0.79752649,  2.15533156,  0.6978161 ],
       [ 0.53017674, -1.11524338, -0.19813357]])

In [17]:
np.random.randint(0, 10, (3, 3))

array([[1, 4, 6],
       [2, 3, 4],
       [6, 4, 5]])

In [18]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# uninitialized array
np.empty(3)

array([1., 1., 1.])

### NumPy Standard Data Types

In [20]:
np.zeros(10, dtype="int16")
np.zeros(10, dtype=np.int16)
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])